### PR TITLE
Fixed OnContextMenuOpen not being called correctly.

### PR DESCRIPTION
**Pull request by alexgrist**

### CODE REVIEW

**Comment by MattJeanes** [comment]
What does this change do exactly?

**Comment by alexgrist** [comment]
Gamemode functions are called as GAMEMODE:HookName() which means that the first argument passed is automatically GAMEMODE (or self). Any gamemodes that use the OnContextMenuOpen hook and use the "self" variable will error due to GAMEMODE not being passed in your override.

**Comment by MattJeanes** [comment]
Oh I see, yeah just saw the whole file and what it's doing. Okay I'm cool with this pull req, but while I have permission to merge it I'll have to leave it to @weltensturm to decide.

**Comment by alexgrist** [comment]
Alright, would be good to get this merged so WAC no longer breaks the context menu.

**Pull request merged**
